---
title: "assignment 2"
author: "Ziyi"
date: "2021/9/13"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
set up RStudio
```{r setup_package, warning = FALSE, message = FALSE}
library(tidyverse)
library(tidycensus)
library(sf)
library(tmap) # mapping, install if you don't have it
set.seed(717)
```
## Load data from {tidycensus}
I chose the live Alone variable from the data.
And pick neighborhood near center city and south Philadelphia.

```{r acs_vars, cache = TRUE, message = FALSE, warning = FALSE, results=FALSE}
acs_variable_list.2019 <- load_variables(2019, #year
                                         "acs5", #five year ACS estimates
                                         cache = TRUE)

census_api_key("2b9294145b5160a675319efda2cdba7b5e3d4807", overwrite = TRUE)

acs_vars <- c("B09021_001E", #Estimate!!Total
              "B09021_002E") #Estimate!!Total:!!Lives alone

myTracts <- c("42101020300", 
              "42101017202",
              "42101006000", 
              "42101006900",
              "42101003800")

acsTractsPHL.2019.sf <- get_acs(geography = "tract",
                                year = 2019, 
                                variables = acs_vars, 
                                geometry = TRUE, 
                                state = "PA", 
                                county = "Philadelphia", 
                                output = "wide") %>% 
  dplyr::select (GEOID, NAME, all_of(acs_vars)) %>%
  rename (total_pop.2019 = B09021_001E,
          total_alone.2019 = B09021_002E) %>%
  mutate(pctalone.2019 = total_alone.2019/total_pop.2019) %>%
  mutate(mtAiry = ifelse(GEOID %in% myTracts, "MT AIRY", "REST OF PHILADELPHIA"))
```

## Transform to WGS84 with {sf}

```{r}
acsTractsPHL.2019.sf <- acsTractsPHL.2019.sf %>% 
  st_transform(crs = "EPSG:4326")
```

## Plot with {ggplot2}

```{r ggplot_geom_sf, warning = FALSE, echo = FALSE}
ggplot()+
  geom_sf(data = acsTractsPHL.2019.sf, aes(fill = pctalone.2019),
          color = "transparent")+
  geom_sf(data = acsTractsPHL.2019.sf %>%
            filter(mtAiry == "MT AIRY") %>%
            st_union(),
          color = "white",
          fill = "transparent")+
  labs(
    title = "Percentage of people live alone",
    subtitle = "2019",
    caption = "Data: US Census Bureau, ACS 5-year estimates")
```